# Generated by Django 5.0.6 on 2024-06-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupRoleMapping',
        ),
    ]
