# Generated by Django 5.0.6 on 2024-06-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0002_initial'),
    ]

    operations = [
    ]
