# Generated by Django 5.0.6 on 2024-06-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupRoleMapping',
        ),
    ]
