# Generated by Django 5.0.6 on 2024-06-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0003_auto_20240629_1933'),
    ]

    operations = [
    ]
