# Generated by Django 5.0.6 on 2024-06-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dhcp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPSubnet',
            new_name='ScopePerm',
        ),
    ]
