# Generated by Django 5.0.6 on 2024-06-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0002_rename_ipsubnet_scopeperm'),
    ]

    operations = [
    ]
